[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.5"

[profile.release]
debug = true
lto = "fat"
panic = "abort"

[[bench]]
name = "bench"
harness = false

[dependencies]
mimalloc = { version = "*", default-features = false }
regex = "1.11.1"
